[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ===== 16MB FLASH + 8MB PSRAM НАСТРОЙКИ =====
board_upload.flash_size = 16MB
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = default_16MB.csv
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC
    -D CONFIG_SPIRAM_IGNORE_NOTFOUND

lib_deps = 
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
